FROM golang:alpine as builder

LABEL maintainer="Marvin Collins <marvin@appslab.co.ke>"
WORKDIR /go/src/app

ENV GO111MODULE=on
RUN go install github.com/cespare/reflex@latest

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o ./run .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /go/src/app/.env.local /root/.env
COPY --from=builder /go/src/app/certs/ /root/certs
COPY --from=builder /go/src/app/run .

EXPOSE 8080
CMD ["./run"]
